PUT   http://localhost:8080/events/1
Content-type:application/json

{
    "name":"updated Test event",
    "description":"A test event updated",
    "location": "A test location",
    "dateTime":"2025-01-01T15:30:00.000Z"
}